### PR TITLE
feat: dry-run input

### PR DESCRIPTION
**Pull request by abenhlal**
## Description

👋 Hi @google-github-actions team,
First of all, I want to thank you for your work.
The purpose of this "PR" is to provide a "dry-run" input, in order to know the behavior of "release-please" when a pull request will be merged.

## How

- `build` functions are called instead of `create` functions

### Additional Inputs

- `dry-run`: boolean

### Additional outputs

- `dry-pr`
- `dry-prs`
- `dry-release`
- `dry-releases`

## Related issues
- https://github.com/google-github-actions/release-please-action/issues/547

## Example outputs

<details>
<summary>dry-pr</summary>

```json
{
  "title": {
    "version": {
      "major": 0,
      "minor": 2,
      "patch": 0
    },
    "component": "",
    "targetBranch": "feat-release-please-dry-run",
    "pullRequestTitlePattern": "chore${scope}: release${component} ${version}",
    "matchPattern": {}
  },
  "body": {
    "header": ":robot: I have created a release *beep* *boop*",
    "footer": "This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).",
    "releaseData": [
      {
        "component": "",
        "version": {
          "major": 0,
          "minor": 2,
          "patch": 0
        },
        "notes": "## [0.2.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.2.0) (2022-11-06)\n\n\n### Features\n\n* test dry-run input ([111ab58](https://github.com/CborgDB/training/commit/111ab5867c93058ec5c28274cabc8b6786ebb454))\n\n\n### Bug Fixes\n\n* version number in  CMakeLists.txt ([b24d975](https://github.com/CborgDB/training/commit/b24d975cf619da84dd69ece491dce110020d0eeb))\n* version number in manifest 7 ([3c0567f](https://github.com/CborgDB/training/commit/3c0567fc95810bc85ab91eda91082d813631086d))"
      }
    ],
    "useComponents": false
  },
  "updates": [
    {
      "path": "CHANGELOG.md",
      "createIfMissing": true,
      "updater": {
        "version": {
          "major": 0,
          "minor": 2,
          "patch": 0
        },
        "changelogEntry": "## [0.2.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.2.0) (2022-11-06)\n\n\n### Features\n\n* test dry-run input ([111ab58](https://github.com/CborgDB/training/commit/111ab5867c93058ec5c28274cabc8b6786ebb454))\n\n\n### Bug Fixes\n\n* version number in  CMakeLists.txt ([b24d975](https://github.com/CborgDB/training/commit/b24d975cf619da84dd69ece491dce110020d0eeb))\n* version number in manifest 7 ([3c0567f](https://github.com/CborgDB/training/commit/3c0567fc95810bc85ab91eda91082d813631086d))",
        "versionHeaderRegex": {}
      },
      "content": "# Changelog\n\n## [0.2.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.2.0) (2022-11-06)\n\n\n### Features\n\n* test dry-run input ([111ab58](https://github.com/CborgDB/training/commit/111ab5867c93058ec5c28274cabc8b6786ebb454))\n\n\n### Bug Fixes\n\n* version number in  CMakeLists.txt ([b24d975](https://github.com/CborgDB/training/commit/b24d975cf619da84dd69ece491dce110020d0eeb))\n* version number in manifest 7 ([3c0567f](https://github.com/CborgDB/training/commit/3c0567fc95810bc85ab91eda91082d813631086d))\n\n## [0.1.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.1.0) (2022-10-19)\n\n\n### Features\n\n* **changelog:** first version with changelog ([27d9a26](https://github.com/CborgDB/training/commit/27d9a26c0e9b8bf0107460dea86467dd7a18b329))\n\n\n### Bug Fixes\n\n* version number ([8b59c47](https://github.com/CborgDB/training/commit/8b59c47ba9641ad4ac0cc3021ed761b9335b40ba))\n* version number in manifest ([9a4d03a](https://github.com/CborgDB/training/commit/9a4d03ac24a0e2695dd9ab27ddec0038a2ca50e4))\n* version number in manifest 2 ([eae40d2](https://github.com/CborgDB/training/commit/eae40d27a9d4a3f187a02e1f18c6095bad93cbb9))\n* version number in manifest 3 ([baaf4c1](https://github.com/CborgDB/training/commit/baaf4c1d61eee149d6fdef872d8667ed09c445b2))\n* version number in manifest 6 ([682aea2](https://github.com/CborgDB/training/commit/682aea27764c5e2e9bc0b2a2caafaeb6bcb61e67))\n\n\n### Reverts\n\n* **cz:** test ([619651f](https://github.com/CborgDB/training/commit/619651f394a694ef9def11c363669cc7b8cec7d5))\n",
      "originalContent": "# Changelog\n\n## [0.1.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.1.0) (2022-10-19)\n\n\n### Features\n\n* **changelog:** first version with changelog ([27d9a26](https://github.com/CborgDB/training/commit/27d9a26c0e9b8bf0107460dea86467dd7a18b329))\n\n\n### Bug Fixes\n\n* version number ([8b59c47](https://github.com/CborgDB/training/commit/8b59c47ba9641ad4ac0cc3021ed761b9335b40ba))\n* version number in manifest ([9a4d03a](https://github.com/CborgDB/training/commit/9a4d03ac24a0e2695dd9ab27ddec0038a2ca50e4))\n* version number in manifest 2 ([eae40d2](https://github.com/CborgDB/training/commit/eae40d27a9d4a3f187a02e1f18c6095bad93cbb9))\n* version number in manifest 3 ([baaf4c1](https://github.com/CborgDB/training/commit/baaf4c1d61eee149d6fdef872d8667ed09c445b2))\n* version number in manifest 6 ([682aea2](https://github.com/CborgDB/training/commit/682aea27764c5e2e9bc0b2a2caafaeb6bcb61e67))\n\n\n### Reverts\n\n* **cz:** test ([619651f](https://github.com/CborgDB/training/commit/619651f394a694ef9def11c363669cc7b8cec7d5))\n",
      "patch": "Index: CHANGELOG.md\n===================================================================\n--- CHANGELOG.md\n+++ CHANGELOG.md\n@@ -1,6 +1,19 @@\n # Changelog\n \n+## [0.2.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.2.0) (2022-11-06)\n+\n+\n+### Features\n+\n+* test dry-run input ([111ab58](https://github.com/CborgDB/training/commit/111ab5867c93058ec5c28274cabc8b6786ebb454))\n+\n+\n+### Bug Fixes\n+\n+* version number in  CMakeLists.txt ([b24d975](https://github.com/CborgDB/training/commit/b24d975cf619da84dd69ece491dce110020d0eeb))\n+* version number in manifest 7 ([3c0567f](https://github.com/CborgDB/training/commit/3c0567fc95810bc85ab91eda91082d813631086d))\n+\n ## [0.1.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.1.0) (2022-10-19)\n \n \n ### Features\n"
    },
    {
      "path": ".release-please-manifest.json",
      "createIfMissing": false,
      "updater": {
        "version": {
          "major": 0,
          "minor": 2,
          "patch": 0
        },
        "versionsMap": {}
      },
      "content": "{\".\":\"0.2.0\"}\n",
      "originalContent": "{\".\":\"0.1.0\"}\n",
      "patch": "Index: .release-please-manifest.json\n===================================================================\n--- .release-please-manifest.json\n+++ .release-please-manifest.json\n@@ -1,1 +1,1 @@\n-{\".\":\"0.1.0\"}\n+{\".\":\"0.2.0\"}\n"
    }
  ],
  "labels": [
    "autorelease: pending"
  ],
  "headRefName": "release-please--branches--feat-release-please-dry-run",
  "version": {
    "major": 0,
    "minor": 2,
    "patch": 0
  },
  "draft": false
}
```

</details>

<details>
<summary>dry-prs (like dry-pr but in array)</summary>

```json
[
  {
    "title": {
      "version": {
        "major": 0,
        "minor": 2,
        "patch": 0
      },
      "component": "",
      "targetBranch": "feat-release-please-dry-run",
      "pullRequestTitlePattern": "chore${scope}: release${component} ${version}",
      "matchPattern": {}
    },
    "body": {
      "header": ":robot: I have created a release *beep* *boop*",
      "footer": "This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).",
      "releaseData": [
        {
          "component": "",
          "version": {
            "major": 0,
            "minor": 2,
            "patch": 0
          },
          "notes": "## [0.2.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.2.0) (2022-11-06)\n\n\n### Features\n\n* test dry-run input ([111ab58](https://github.com/CborgDB/training/commit/111ab5867c93058ec5c28274cabc8b6786ebb454))\n\n\n### Bug Fixes\n\n* version number in  CMakeLists.txt ([b24d975](https://github.com/CborgDB/training/commit/b24d975cf619da84dd69ece491dce110020d0eeb))\n* version number in manifest 7 ([3c0567f](https://github.com/CborgDB/training/commit/3c0567fc95810bc85ab91eda91082d813631086d))"
        }
      ],
      "useComponents": false
    },
    "updates": [
      {
        "path": "CHANGELOG.md",
        "createIfMissing": true,
        "updater": {
          "version": {
            "major": 0,
            "minor": 2,
            "patch": 0
          },
          "changelogEntry": "## [0.2.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.2.0) (2022-11-06)\n\n\n### Features\n\n* test dry-run input ([111ab58](https://github.com/CborgDB/training/commit/111ab5867c93058ec5c28274cabc8b6786ebb454))\n\n\n### Bug Fixes\n\n* version number in  CMakeLists.txt ([b24d975](https://github.com/CborgDB/training/commit/b24d975cf619da84dd69ece491dce110020d0eeb))\n* version number in manifest 7 ([3c0567f](https://github.com/CborgDB/training/commit/3c0567fc95810bc85ab91eda91082d813631086d))",
          "versionHeaderRegex": {}
        },
        "content": "# Changelog\n\n## [0.2.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.2.0) (2022-11-06)\n\n\n### Features\n\n* test dry-run input ([111ab58](https://github.com/CborgDB/training/commit/111ab5867c93058ec5c28274cabc8b6786ebb454))\n\n\n### Bug Fixes\n\n* version number in  CMakeLists.txt ([b24d975](https://github.com/CborgDB/training/commit/b24d975cf619da84dd69ece491dce110020d0eeb))\n* version number in manifest 7 ([3c0567f](https://github.com/CborgDB/training/commit/3c0567fc95810bc85ab91eda91082d813631086d))\n\n## [0.1.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.1.0) (2022-10-19)\n\n\n### Features\n\n* **changelog:** first version with changelog ([27d9a26](https://github.com/CborgDB/training/commit/27d9a26c0e9b8bf0107460dea86467dd7a18b329))\n\n\n### Bug Fixes\n\n* version number ([8b59c47](https://github.com/CborgDB/training/commit/8b59c47ba9641ad4ac0cc3021ed761b9335b40ba))\n* version number in manifest ([9a4d03a](https://github.com/CborgDB/training/commit/9a4d03ac24a0e2695dd9ab27ddec0038a2ca50e4))\n* version number in manifest 2 ([eae40d2](https://github.com/CborgDB/training/commit/eae40d27a9d4a3f187a02e1f18c6095bad93cbb9))\n* version number in manifest 3 ([baaf4c1](https://github.com/CborgDB/training/commit/baaf4c1d61eee149d6fdef872d8667ed09c445b2))\n* version number in manifest 6 ([682aea2](https://github.com/CborgDB/training/commit/682aea27764c5e2e9bc0b2a2caafaeb6bcb61e67))\n\n\n### Reverts\n\n* **cz:** test ([619651f](https://github.com/CborgDB/training/commit/619651f394a694ef9def11c363669cc7b8cec7d5))\n",
        "originalContent": "# Changelog\n\n## [0.1.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.1.0) (2022-10-19)\n\n\n### Features\n\n* **changelog:** first version with changelog ([27d9a26](https://github.com/CborgDB/training/commit/27d9a26c0e9b8bf0107460dea86467dd7a18b329))\n\n\n### Bug Fixes\n\n* version number ([8b59c47](https://github.com/CborgDB/training/commit/8b59c47ba9641ad4ac0cc3021ed761b9335b40ba))\n* version number in manifest ([9a4d03a](https://github.com/CborgDB/training/commit/9a4d03ac24a0e2695dd9ab27ddec0038a2ca50e4))\n* version number in manifest 2 ([eae40d2](https://github.com/CborgDB/training/commit/eae40d27a9d4a3f187a02e1f18c6095bad93cbb9))\n* version number in manifest 3 ([baaf4c1](https://github.com/CborgDB/training/commit/baaf4c1d61eee149d6fdef872d8667ed09c445b2))\n* version number in manifest 6 ([682aea2](https://github.com/CborgDB/training/commit/682aea27764c5e2e9bc0b2a2caafaeb6bcb61e67))\n\n\n### Reverts\n\n* **cz:** test ([619651f](https://github.com/CborgDB/training/commit/619651f394a694ef9def11c363669cc7b8cec7d5))\n",
        "patch": "Index: CHANGELOG.md\n===================================================================\n--- CHANGELOG.md\n+++ CHANGELOG.md\n@@ -1,6 +1,19 @@\n # Changelog\n \n+## [0.2.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.2.0) (2022-11-06)\n+\n+\n+### Features\n+\n+* test dry-run input ([111ab58](https://github.com/CborgDB/training/commit/111ab5867c93058ec5c28274cabc8b6786ebb454))\n+\n+\n+### Bug Fixes\n+\n+* version number in  CMakeLists.txt ([b24d975](https://github.com/CborgDB/training/commit/b24d975cf619da84dd69ece491dce110020d0eeb))\n+* version number in manifest 7 ([3c0567f](https://github.com/CborgDB/training/commit/3c0567fc95810bc85ab91eda91082d813631086d))\n+\n ## [0.1.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.1.0) (2022-10-19)\n \n \n ### Features\n"
      },
      {
        "path": ".release-please-manifest.json",
        "createIfMissing": false,
        "updater": {
          "version": {
            "major": 0,
            "minor": 2,
            "patch": 0
          },
          "versionsMap": {}
        },
        "content": "{\".\":\"0.2.0\"}\n",
        "originalContent": "{\".\":\"0.1.0\"}\n",
        "patch": "Index: .release-please-manifest.json\n===================================================================\n--- .release-please-manifest.json\n+++ .release-please-manifest.json\n@@ -1,1 +1,1 @@\n-{\".\":\"0.1.0\"}\n+{\".\":\"0.2.0\"}\n"
      }
    ],
    "labels": [
      "autorelease: pending"
    ],
    "headRefName": "release-please--branches--feat-release-please-dry-run",
    "version": {
      "major": 0,
      "minor": 2,
      "patch": 0
    },
    "draft": false
  }
]
```

</details>

<details>
<summary>dry_release</summary>

```json
{
  "name": "v0.2.0",
  "tag": {
    "version": {
      "major": 0,
      "minor": 2,
      "patch": 0
    },
    "component": "",
    "separator": "-",
    "includeV": true
  },
  "notes": "## [0.2.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.2.0) (2022-11-06)\n\n\n### Features\n\n* test dry-run input ([7c048d7](https://github.com/CborgDB/training/commit/7c048d7e5ad27a50f2f7f3da0a8907bc44db5577))\n\n\n### Bug Fixes\n\n* version number in  CMakeLists.txt ([b24d975](https://github.com/CborgDB/training/commit/b24d975cf619da84dd69ece491dce110020d0eeb))\n* version number in manifest 7 ([3c0567f](https://github.com/CborgDB/training/commit/3c0567fc95810bc85ab91eda91082d813631086d))",
  "sha": "7b642634c571f85fd71a60890d6c35682867dc44",
  "path": ".",
  "pullRequest": {
    "headBranchName": "release-please--branches--feat-release-please-dry-run",
    "baseBranchName": "feat-release-please-dry-run",
    "number": 43,
    "title": "chore(feat-release-please-dry-run): release 0.2.0",
    "body": ":robot: I have created a release *beep* *boop*\n---\n\n\n## [0.2.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.2.0) (2022-11-06)\n\n\n### Features\n\n* test dry-run input ([7c048d7](https://github.com/CborgDB/training/commit/7c048d7e5ad27a50f2f7f3da0a8907bc44db5577))\n\n\n### Bug Fixes\n\n* version number in  CMakeLists.txt ([b24d975](https://github.com/CborgDB/training/commit/b24d975cf619da84dd69ece491dce110020d0eeb))\n* version number in manifest 7 ([3c0567f](https://github.com/CborgDB/training/commit/3c0567fc95810bc85ab91eda91082d813631086d))\n\n---\nThis PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).",
    "labels": [
      "autorelease: pending"
    ],
    "files": [],
    "sha": "7b642634c571f85fd71a60890d6c35682867dc44"
  }
}
```

</details>

<details>
<summary>dry_releases (like dry_releases but in array)</summary>

```json
[
  {
    "name": "v0.2.0",
    "tag": {
      "version": {
        "major": 0,
        "minor": 2,
        "patch": 0
      },
      "component": "",
      "separator": "-",
      "includeV": true
    },
    "notes": "## [0.2.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.2.0) (2022-11-06)\n\n\n### Features\n\n* test dry-run input ([7c048d7](https://github.com/CborgDB/training/commit/7c048d7e5ad27a50f2f7f3da0a8907bc44db5577))\n\n\n### Bug Fixes\n\n* version number in  CMakeLists.txt ([b24d975](https://github.com/CborgDB/training/commit/b24d975cf619da84dd69ece491dce110020d0eeb))\n* version number in manifest 7 ([3c0567f](https://github.com/CborgDB/training/commit/3c0567fc95810bc85ab91eda91082d813631086d))",
    "sha": "7b642634c571f85fd71a60890d6c35682867dc44",
    "path": ".",
    "pullRequest": {
      "headBranchName": "release-please--branches--feat-release-please-dry-run",
      "baseBranchName": "feat-release-please-dry-run",
      "number": 43,
      "title": "chore(feat-release-please-dry-run): release 0.2.0",
      "body": ":robot: I have created a release *beep* *boop*\n---\n\n\n## [0.2.0](https://github.com/CborgDB/training/compare/v0.1.0...v0.2.0) (2022-11-06)\n\n\n### Features\n\n* test dry-run input ([7c048d7](https://github.com/CborgDB/training/commit/7c048d7e5ad27a50f2f7f3da0a8907bc44db5577))\n\n\n### Bug Fixes\n\n* version number in  CMakeLists.txt ([b24d975](https://github.com/CborgDB/training/commit/b24d975cf619da84dd69ece491dce110020d0eeb))\n* version number in manifest 7 ([3c0567f](https://github.com/CborgDB/training/commit/3c0567fc95810bc85ab91eda91082d813631086d))\n\n---\nThis PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).",
      "labels": [
        "autorelease: pending"
      ],
      "files": [],
      "sha": "7b642634c571f85fd71a60890d6c35682867dc44"
    }
  }
]
```

</details>

## Tests

I am having some issues with testing.

## Additional Information
I am not a JavaScript developer

## Example usage

<details>
<summary> [Screenshot | Workflow] Comment using release-please-action outputs</summary>

comment-release-please-action

- Workflow

```yaml

name: ✨ release-please dry-run

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: abenhlal/release-please-action@feat-dry-run-build
        id: release
        with:
          default-branch: feat-release-please-dry-run
          command: manifest
          dry-run: 'true'
    outputs:
      dry_pr: ${{ steps.release.outputs.dry_pr }}
      dry_prs: ${{ steps.release.outputs.dry_prs }}
      dry_release: ${{ steps.release.outputs.dry_release }}
      dry_releases: ${{ steps.release.outputs.dry_releases }}
  comments:
    needs: release-please
    runs-on: ubuntu-latest
    strategy:
      matrix:
        prs: ${{ fromJson(needs.release-please.outputs.dry_prs) }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            // For pullRequestTitlePattern
            const scope = "${{ matrix.prs.title.targetBranch }}" !== "" ? '(${{ matrix.prs.title.targetBranch }})' : '';
            const component = "${{ matrix.prs.title.component }}" !== "" ? ' ${{ matrix.prs.title.component }}' : '';
            const version = ${{ matrix.prs.title.version }} !== undefined ? `${{ matrix.prs.title.version.major }}.${{ matrix.prs.title.version.minor }}.${{ matrix.prs.title.version.patch }}`: '';
            const branch = "${{ matrix.prs.title.targetBranch }}"

            // For Body
            const bodyDelimiter = "---"
            const bodyHeader = "${{ matrix.prs.body.header }}"
            const bodyFooter = "${{ matrix.prs.body.footer }}"
            const bodyNotes = ${{ matrix.prs.body.useComponents }} ? "" : `${{ join(matrix.prs.body.releaseData.*.notes, '\n\n') }}`;
            let body = `\n\n${bodyHeader}\n\n${bodyDelimiter}\n\n${bodyNotes}\n\n${bodyDelimiter}\n\n${bodyFooter}\n\n`
            body = body.replace(/\n/gm, '\n> ');

            // For Updates
            const updates = ${{ toJson(matrix.prs.updates) }}
            let patches = ""
            updates.forEach(update  => (patches += "\n<details>\n<summary>"+update.path+"</summary>\n\n```diff\n"+update.patch+"\n```\n\n</details>\n"))

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              **title:** ${{ matrix.prs.title.pullRequestTitlePattern }}
              **branch:** ${{ matrix.prs.headRefName }}
              **draft:** ${{ matrix.prs.draft }}
              **body:** ${body}
              **updates**: ${patches}
              `
            })


```

</details>

### CODE REVIEW

**Comment by abenhlal** [comment]
> Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> View this [failed invocation](https://github.com/google-github-actions/release-please-action/pull/654/checks?check_run_id=9320609896) of the CLA check for more information.
> 
> For the most up to date status, view the checks section at the bottom of the pull request.

Sorry, this is my first contribution 😉

**Comment by Eriwyr** [comment]
Awesome !

**Comment by shunkakinoki** [comment]
Any updates on this! Would love to see it merged 🙇‍♂️

**Comment by abenhlal** [comment]
> Any updates on this! Would love to see it merged :bowing_man: 

:man_shrugging:

**Comment by phuongdinh1411** [comment]
Hi, any updates on this!

**Comment by chingor13** [comment]
Apologies for not getting to this and thank you for opening it in the first place. For maintainability of this action, a dry-run option is not something we can support/maintain at this time.

We highly recommend configuring your repository with a manifest configuration (see [docs](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md)). This type of configuration should work regardless of the invocation method (GitHub app, GitHub action, CLI invocation) The CLI tool has a `--dry-run` option which will better debug your configuration.

**Comment by Cavaler** [comment]
That's actually extremely disappointing. Having to install npm, release-please CLI, manually run it - all in order to just read the current version, for example?

**Pull request closed without merging**
