### PR TITLE
feat: Add 'initial-version' input

### LINKED ISSUE #683: Add initial-version configuration option
### TL;DR

Quote from the [latest Semantic Versioning specification](https://semver.org/)

> **How should I deal with revisions in the 0.y.z initial development phase?**
> The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

It is becoming more commonplace to see the convention of 0.x.y as pre-releases under active development, and 1.0.0 as a "stable production release".

To allow this convention, we would like to be able to set initial version to 0.1.0 on the github action and have this honoured by the release process. 

### Detailed design

Something like this would be great.

```
    steps:
      - name: release-please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          initial-release: v0.1.0
          # BREAKING CHANGE commits only bump semver minor level, if version < 1.0.0
          bump-minor-pre-major: true
          # feat commits bump semver patch level instead of minor, if version < 1.0.0
          bump-patch-for-minor-pre-major: true
```

### Additional information

- release-please seems to [implement this](https://github.com/googleapis/release-please/search?q=initialVersion) in some way.

- Related to #425 . 
When 0.x.y is the current version we should be sure to respect the bump settings: 
`bump-minor-pre-major: true`and `bump-patch-for-minor-pre-major: true`

### PR DESCRIPTION
**Pull request by baolsen**
Closes #683

### CODE REVIEW

**Comment by baolsen** [comment]
@bcoe please take a look when you can.

**Comment by baolsen** [comment]
@bcoe bump

**Comment by baolsen** [comment]
Hey @chingor13 , could you take a look?

**Comment by baolsen** [comment]
@chingor13  bump :)

**Comment by chingor13** [comment]
Apologies, but for maintainability, we cannot continue to pass through every configuration option in the form of action inputs.

In v4, we are removing most configuration options which can be set in the manifest configuration file. This will make updating the action with the latest version/features easier and allow folks to debug their configuration using the `release-please` CLI.

**Pull request closed without merging**
