### PR TITLE
feat(release-please)!: consolidate manifest and individual releasers

### PR DESCRIPTION
**Pull request by bcoe**
Major update to release-please which consolidates the manifest and single
releaser behavior into a single set of strategies, which can be used
on both split and mono-repos.

feat: adds support for draft pull requests.
feat: adds support for draft releases.
refactor!: if switching to manifest releaser, release_created will only be set if "." path is published.
refactor!: switch to using @actions/core getBooleanInput, accepted values for `true` = ["true", "True", "TRUE"], accepted values for `false` = ["false", "False", "FALSE"].

### CODE REVIEW

**Comment by kalosisz** [comment]
hey @bcoe, I believe this would allow to create draft PR, but not draft Github releases. Am I wrong?

**Comment by live627** [comment]
Can you  add documentation for  upgrading?

**Comment by kalosisz** [comment]
Could you please allow this args to set? Thanks

https://github.com/googleapis/release-please/blob/28bc76b35d9e1eff218a5be1b9b8cebb4b1e6f9d/src/bin/release-please.ts#L189-L196

**Comment by bcoe** [comment]
> Could you please allow this args to set? Thanks

@kalosisz sure thing.

> Can you add documentation for upgrading?

I don't believe there will ultimately be any major changes that need to be made to upgrade. There is some underlying behavior that changes, such as the branch naming convention, which does make this a breaking change (but shouldn't affect most people).

**Comment by goatwu1993** [comment]
@bcoe maybe bump the action/core to latest(1.6.0) as well since this is a major release?

Release note: https://github.com/actions/toolkit/blob/main/packages/core/RELEASES.md

1.3.0 has getBooleanInput. However, it provides less valid boolean input.(https://github.com/actions/toolkit/blob/daf8bb00606d37ee2431d9b1596b88513dcf9c59/packages/core/src/core.ts#L171)

1.4.0 has getMultilineInput. Which https://github.com/googleapis/release-please/pull/1157 may take advantage for inputing extra-files

**Comment by chingor13** [comment]
> 1.3.0 `@action/core` introduced `getBooleanInput`. Since `core.getBooleanInput` accepts fewer strings, it is a BREAKING change. Good timing to remove housemade`getBooleanInput` and use `core.getBooleanInput` (if you like to). String accepted can be found [here](https://github.com/actions/toolkit/blob/daf8bb00606d37ee2431d9b1596b88513dcf9c59/packages/core/src/core.ts#L171)

Switching the boolean helper sounds like a good change to make before releasing v3 of the action. Perhaps in a follow-up PR before the new tag?

> 1.4.0 `@action/core` introduced `getMultilineInput` which returns `string[]`, which [googleapis/release-please#1157](https://github.com/googleapis/release-please/pull/1157) may take advantage of.

We can use this without a breaking change when surfacing new options

**Review by chingor13 — APPROVED** [review]

**Pull request merged**
