### PR TITLE
docs: document PHP releaser

### PR DESCRIPTION
**Pull request by setnemo**

### CODE REVIEW

**Comment by bcoe** [comment]
@setnemo I'm wondering if there was just a hiccup with automation and I failed to land the right build; the only other thing I can think of is perhaps it was the switch from npm's v1 lock to v2 lock (_I don't know why this would affect things, but I switched back for the time being [here](https://github.com/google-github-actions/release-please-action/pull/352)).

Could I bother you to:

1. test out the latest build of `relese-please-action`, to make sure it works for you (you should be able to run your action against the `main` branch of this repo).
2. update this PR to just update README, not check in compiled code.

Thank you for your contributions.

**Comment by setnemo** [comment]
The same...


https://github.com/setnemo/asterisk-notation/runs/3538696653?check_suite_focus=true

**Comment by setnemo** [comment]
I don't know how, but version in Marketplace is old

**Comment by bcoe** [comment]
@setnemo I haven't released yet, so rather than setting `v2`.

Do `GoogleCloudPlatform/release-please-action#main`

**Comment by setnemo** [comment]
@bcoe Awesome, it's work correctly! Thank you for your advice!

**Review by bcoe — APPROVED** [review]

**Pull request merged**
