### PR TITLE
[DO NOT MERGE] build: publish testing release for helm

### PR DESCRIPTION
**Pull request by bcoe**
Testing build for helm.

### CODE REVIEW

**Comment by pragmaticivan** [comment]
Very much looking forward to this helm feature! Awesome!

**Comment by pragmaticivan** [comment]
FYI, very likely that it will break until https://github.com/google-github-actions/release-please-action/pull/217 is merged.

**Comment by abhinavkhanna-sf** [comment]
Run GoogleCloudPlatform/release-please-action**@test-helm**
  with:
    token: ***
    release-type: helm
Error: release-please failed: gr.createRelease is not a function

**Comment by pragmaticivan** [comment]
@abhinavkhanna-sf this PR is outdated

**Comment by bcoe** [comment]
@abhinavkhanna-sf this should now be fixed on the main branch.

**Pull request closed without merging**
