### PR TITLE
docs(readme): Add `changelog-type`

### PR DESCRIPTION
**Pull request by wraithgar**
Adds `changelog-type` option to the readme.

### CODE REVIEW

**Comment by wraithgar** [comment]
It looks like this was removed in v3?

**Comment by bcoe** [comment]
@wraithgar I don't believe we intentionally removed this functionality in the parent `release-please`, but we should make sure it's supported before we document the config setting.

**Comment by bcoe** [comment]
@chingor13 happen to know if `changelog-type` is again supported?

**Comment by andrewesweet** [comment]
My observation is that this action gives a different meaning to `changelog-type` that in release-please itself. Therefore, to answer @bcoe's question, I do not think `changelog-type` is supported right now. Resolving this was my motivation for #474.

**Review by bcoe — APPROVED** [review]

**Review by bcoe — APPROVED** [review]

**Review by bcoe — CHANGES_REQUESTED** [review]
Looks like @chingor13 might need to take a closer look, based on @andrewesweet's comments -- we should make sure the meaning is equivalent in the action and the CLI.

**Pull request closed without merging**
